# service: backend-api

# provider:
#   name: aws
#   runtime: nodejs14.x
#   stage: dev
#   region: us-east-1

# functions:
#   createBusiness:
#     handler: handler.createBusiness  # Ensure this is pointing to your handler.js
#     events:
#       - http:
#           path: api/business-detail
#           method: post

#   getBusiness:
#     handler: handler.getBusiness  # Ensure this is pointing to your handler.js
#     events:
#       - http:
#           path: api/business-detail/{id}
#           method: get

# plugins:
#   - serverless-offline






# service: backend-api

# provider:
#   name: aws
#   runtime: nodejs14.x
#   stage: dev
#   region: us-east-1

# functions:
#   createBusiness:
#     handler: handler.createBusiness
#     events:
#       - http:
#           path: api/business-detail
#           method: post

#   getBusiness:
#     handler: handler.getBusiness
#     events:
#       - http:
#           path: api/business-detail/{id}
#           method: get

#   createBankDetails:
#     handler: handler.createBankDetails
#     events:
#       - http:
#           path: api/bank-details
#           method: post

#   getBankDetails:
#     handler: handler.getBankDetails
#     events:
#       - http:
#           path: api/bank-details/{id}
#           method: get

# plugins:
#   - serverless-offline








service: backend-api
functions:
  createBusiness:
    handler: handler.createBusiness
    events:
      - http:
          path: api/business-detail
          method: post

  getBusiness:
    handler: handler.getBusiness
    events:
      - http:
          path: api/business-detail/{id}
          method: get

  createBankDetails:
    handler: handler.createBankDetails
    events:
      - http:
          path: api/bank-details
          method: post

  getBankDetails:
    handler: handler.getBankDetails
    events:
      - http:
          path: api/bank-details/{id}
          method: get

  createCompanyDetails:
    handler: handler.createCompanyDetails
    events:
      - http:
          path: api/company-details
          method: post

  getCompanyDetails:
    handler: handler.getCompanyDetails
    events:
      - http:
          path: api/company-details/{id}
          method: get

  createTradingDetails:
    handler: handler.createTradingDetails
    events:
      - http:
          path: api/trading-details
          method: post

  getTradingDetails:
    handler: handler.getTradingDetails
    events:
      - http:
          path: api/trading-details/{id}
          method: get

plugins:
  - serverless-offline
